apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: foo
spec:
  releaseName: foo
  serviceAccountName: sa
  chart:
    spec:
      chart: foo
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: helm
        namespace: kube-system
      valuesFiles:
        - values.yaml
  interval: 5m